<?php

return [
    'up' => 'CREATE TABLE IF NOT EXISTS users ( id SERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, is_active SMALLINT NOT NULL DEFAULT 1, activation_token VARCHAR(64) DEFAULT NULL, activated_at TIMESTAMP DEFAULT NULL, reset_token VARCHAR(64) DEFAULT NULL, reset_token_expires_at TIMESTAMP DEFAULT NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), deleted_at TIMESTAMP DEFAULT NULL)',
    'down' => 'DROP TABLE IF EXISTS users',
];
