<?php

return [
    'up' => 'CREATE TABLE IF NOT EXISTS webhooks ( id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, url TEXT NOT NULL, secret TEXT NOT NULL, events TEXT NOT NULL DEFAULT \'[]\', is_active INTEGER NOT NULL DEFAULT 1, description TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP, updated_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS webhook_deliveries ( id INTEGER PRIMARY KEY AUTOINCREMENT, webhook_id INTEGER NOT NULL REFERENCES webhooks(id) ON DELETE CASCADE, event TEXT NOT NULL, url TEXT NOT NULL, payload TEXT, status TEXT NOT NULL DEFAULT \'pending\', http_status INTEGER DEFAULT 0, response_body TEXT, attempt INTEGER NOT NULL DEFAULT 1, created_at TEXT DEFAULT CURRENT_TIMESTAMP)',
    'down' => 'DROP TABLE IF EXISTS webhook_deliveries; DROP TABLE IF EXISTS webhooks',
];
